version: '2'

checks:
  complex-logic:
    enabled: false
  method-complexity:
    enabled: false
  file-lines:
    config:
      threshold: 1000
  method-lines:
    enabled: false
    config:
      threshold: 100
    eslint:
      enabled: true
  return-statements:
    enabled: true
    config:
      threshold: 50
  similar-code:
    enabled: false
    config:
      threshold: 75
  identical-code:
    enabled: false
    config:
      threshold: 75


ratings:
  paths:
    - 'src/**/*.ts'
    - 'src/test/**/*.tsx'
    - '**/*.ts'
    - '**/*.tsx'
exclude_paths:
  - 'node_modules/'
  - 'test/'
  - '.next/'
